CREATE SCHEMA universities;

CREATE TABLE universities.country (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  country_name VARCHAR(100) DEFAULT NULL,
  CONSTRAINT pk_country PRIMARY KEY (id)
);

CREATE TABLE universities.ranking_system (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  system_name VARCHAR(100) DEFAULT NULL,
  CONSTRAINT pk_rs PRIMARY KEY (id)
);

CREATE TABLE universities.ranking_criteria (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  ranking_system_id INT DEFAULT NULL,
  criteria_name VARCHAR(200) DEFAULT NULL,
  CONSTRAINT pk_rc PRIMARY KEY (id),
  CONSTRAINT fk_rc_rs FOREIGN KEY (ranking_system_id) REFERENCES universities.ranking_system (id)
);

CREATE TABLE universities.university (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  country_id INT DEFAULT NULL,
  university_name VARCHAR(200) DEFAULT NULL,
  CONSTRAINT pk_uni PRIMARY KEY (id),
  CONSTRAINT fk_uni_cnt FOREIGN KEY (country_id) REFERENCES universities.country (id)
);

CREATE TABLE universities.university_year (
  university_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  year INT DEFAULT NULL,
  num_students INT DEFAULT NULL,
  student_staff_ratio DECIMAL(6,2) DEFAULT NULL,
  pct_international_students INT DEFAULT NULL,
  pct_female_students INT DEFAULT NULL,
  CONSTRAINT fk_uy_uni FOREIGN KEY (university_id) REFERENCES universities.university (id)
);

CREATE TABLE universities.university_ranking_year (
  university_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  ranking_criteria_id INT DEFAULT NULL,
  year INT DEFAULT NULL,
  score INT DEFAULT NULL,
  CONSTRAINT fk_ury_rc FOREIGN KEY (ranking_criteria_id) REFERENCES universities.ranking_criteria (id),
  CONSTRAINT fk_ury_uni FOREIGN KEY (university_id) REFERENCES universities.university (id)
);